# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skynet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cskynet.proto\x12\x06skynet\"\xd9\x01\n\x08\x43hemical\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06smiles\x18\x02 \x01(\t\x12\x13\n\x0b\x66ingerprint\x18\x03 \x03(\x05\x12\x31\n\x0b\x64\x65scriptors\x18\x04 \x01(\x0b\x32\x1c.skynet.Chemical.Descriptors\x12\x16\n\x0e\x63hembl_targets\x18\x05 \x03(\t\x1aO\n\x0b\x44\x65scriptors\x12\n\n\x02mw\x18\x01 \x01(\x02\x12\x0c\n\x04logp\x18\x02 \x01(\x02\x12\x0c\n\x04tpsa\x18\x03 \x01(\x02\x12\x0b\n\x03hbd\x18\x04 \x01(\x02\x12\x0b\n\x03hba\x18\x05 \x01(\x02\"v\n\x05Vault\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.skynet.Vault.EntriesEntry\x1a@\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.skynet.Chemical:\x02\x38\x01\x42\tZ\x07./protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skynet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _VAULT_ENTRIESENTRY._options = None
  _VAULT_ENTRIESENTRY._serialized_options = b'8\001'
  _CHEMICAL._serialized_start=25
  _CHEMICAL._serialized_end=242
  _CHEMICAL_DESCRIPTORS._serialized_start=163
  _CHEMICAL_DESCRIPTORS._serialized_end=242
  _VAULT._serialized_start=244
  _VAULT._serialized_end=362
  _VAULT_ENTRIESENTRY._serialized_start=298
  _VAULT_ENTRIESENTRY._serialized_end=362
# @@protoc_insertion_point(module_scope)
